name: snaptutorial10
version: '0.1'
summary: snap tutorial summary 
description: |
  	 snap tutorial description

grade: stable #devel 
confinement: strict 

parts:
  gnu-snap:
    source: ./project
    plugin: make
