name: snaptutorial10
version: '0.1'
summary: snap tutorial summary 
description: |
  	 snap tutorial description

grade: devel 
confinement: devmode 

parts:
  gnu-snap:
    source: /home/ubuntu/Documents/project
    plugin: make
